#
# Copyright(c) 2022 Intel. Licensed under the MIT License <http://opensource.org/licenses/MIT>.
#

SPEAR:
  LAUNCH_MODE: "none"
  INSTANCE:
    # EDITOR_EXECUTABLE: "/Users/Shared/Epic_Games/UE_5.5/Engine/Binaries/Mac/UnrealEditor.app"
    # EDITOR_UPROJECT: "/Users/shangzhanz/Desktop/spear/cpp/unreal_projects/SpearSim/SpearSim.uproject"
    # EDITOR_LAUNCH_MODE: "editor"
    COMMAND_LINE_ARGS:
      resx: -1
      resy: -1
    # CLIENT_INTERNAL_TIMEOUT_SECONDS: 100.0 # set this to longer than usual because it takes a few seconds to take a screenshot

    # setting the game viewport to be small when we're rendering offscreen improves performance

    # resx: 128
    # resy: 128
    # renderoffscreen: null
